# Task 1: Calculating the Mean First Passage Matrix for a Regular Markov Chain

**Task description**. The task is to check if a Markov chain is regular, calculate its steady state vector and the mean first passage matrix based on the probability transition matrix.

**Steps for Performing the Task:**

1. Prove that the Markov chain is regular (for this, enough to verify that ${p^k}$ has only non-zero (positive) entries for some integer $k$);

2. Calculate (approximately) the steady state vector $\alpha$ of the chain by calculation of $P^k$ for enough large $t$;

3. Calculate the mean first passage matrix $E$ .

**Student name:** Yan Jingyu

## Solution

I will use Python's Jupyter notebook to complete this task, in which I will use dependency libraries such as numpy and pandas.

### 0. Prepare

Prepare my personal Markov chain probability transition matrix, Import the required libraries and read the transition matrix P.

In [1]:
import pandas as pd
import numpy as np

np.set_printoptions(linewidth=200, threshold=1000, suppress=True, formatter={'float': '{:0.5f}'.format})

def get_my_transition_matrix(xlsx_file, my_name, num_rows=11, use_cols='C:M', ) -> np.ndarray:
    """
    Read my personal transition matrix from an Excel (xlsx) file.
    """
    df = pd.read_excel(xlsx_file)
    row_index = df[df[df.columns[0]] == my_name].index
    if row_index.empty:
        raise FileNotFoundError(
            "transition matrix does not exist, please check the name is correct.")

    df = pd.read_excel(xlsx_file, usecols=use_cols, skiprows=row_index[0] + 1, nrows=num_rows)

    return df.to_numpy()

xlsx_filename = "TaskWorksheets1.xlsx"
my_name = "Yan Jingyu"
P = get_my_transition_matrix(xlsx_filename, my_name)
print(f'My transition matrix P = \n{P}')

My transition matrix P = 
[[0.00000 0.00000 0.00000 0.21064 0.00000 0.18934 0.00000 0.00000 0.27476 0.32526 0.00000]
 [0.00000 0.23340 0.44311 0.00000 0.00000 0.00000 0.00000 0.00000 0.32348 0.00000 0.00000]
 [0.50398 0.00000 0.00000 0.00000 0.00000 0.43275 0.00000 0.00000 0.00000 0.00000 0.06327]
 [0.00000 0.00000 0.49275 0.00000 0.50725 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.30974 0.00000 0.00000 0.00000 0.00000 0.69026 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.02998 0.00000 0.00000 0.00000 0.00000 0.39229 0.00000 0.57774 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.43948 0.00000 0.00000 0.00000 0.00000 0.00000 0.56052]
 [0.47684 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.52316 0.00000 0.00000]
 [0.48492 0.00000 0.00000 0.00000 0.29683 0.00000 0.00000 0.00000 0.00000 0.21825 0.00000]
 [0.00000 0.08205 0.36807 0.00000 0.34591 0.00000 0.00000 0.00000 0.00000 0.00000 0.20397]
 [0.00000 0.00000 0.12319 0.36212 0.12949 0.00000 0.38520 0.0000

In [2]:
def get_example_matrix() -> np.ndarray:
    data_string = """
    0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.6471 0.0000 0.3529 0.0000 0.0000 0.0000 0.3786 0.0000 0.0000 0.0000 0.0000 0.0000 0.1072 0.0000 0.0000 0.0000 0.0000 0.0000 0.5142 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0832 0.1882 0.5169 0.0000 0.0000 0.0000 0.0000 0.0000 0.2116 0.0000 0.3532 0.0000 0.0000 0.0000 0.0518 0.0000 0.0000 0.1502 0.0000 0.0000 0.3496 0.0000 0.0952 0.0000 0.3051 0.0000 0.0000 0.0000 0.0000 0.1197 0.0000 0.0000 0.0000 0.0000 0.0000 0.3114 0.0000 0.0000 0.2638 0.0000 0.0000 0.0000 0.0000 0.1352 0.0000 0.0000 0.0000 0.5226 0.0000 0.0000 0.0000 0.3422 0.0000 0.0000 0.0000 0.0091 0.6572 0.0000 0.3337 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.4596 0.0000 0.0000 0.0000 0.0000 0.1501 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.3903 0.0000 0.0000 0.0000 0.1317 0.0000 0.7591 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.1093 0.0000 0.0000 0.0000 0.0000 0.0000 0.2183 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.2366 0.0000 0.5452 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.6985 0.0000 0.0000 0.0000 0.3015 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.2327 0.0000 0.0000 0.2122 0.2804 0.0000 0.0000 0.0000 0.2747 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.3387 0.0000 0.0000 0.0000 0.0000 0.0000 0.0021 0.0000 0.0000 0.0000 0.3923 0.0000 0.2669 0.0000 0.5361 0.0000 0.0000 0.3795 0.0000 0.0000 0.0612 0.0000 0.0232 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.3084 0.0000 0.0000 0.0000 0.4457 0.0000 0.2145 0.0000 0.0000 0.0314
    """
    data_list = [float(number) for number in data_string.split()]

    mat = np.array(data_list).reshape(15, 15)

    return mat
# P = get_example_matrix()

![](fig1.png)

## 1.  Prove that the Markov chain is regular

Prove that the Markov chain is regular (for this, enough to verify that ${p^k}$ has only non-zero (positive) entries for some integer $k$);

In [3]:
# Use numpy's matrix_power function.
matrix_power = np.linalg.matrix_power

def check_transition_matrix_is_regular_steps(P: np.ndarray, k = 10):
    """
    Check if the P matrix from the 1st to the kth power is entirely positive; if it is, then it is regular.
    """
    # Remark the last power matrix
    P_k = None
    for t in range(1, k + 1):
        P_t = matrix_power(P, t)
        P_k = P_t
        if not (P_t >= 0).all():
            return False, P_k
    
    return True, P_k

k = 10
ret, P_k = check_transition_matrix_is_regular_steps(P, k)
assert ret
print(f"P_k Matrix is regular: {ret}\n")
print(f'P_{k} Matrix = \n{P_k}')

P_k Matrix is regular: True

P_10 Matrix = 
[[0.18519 0.00939 0.06518 0.04940 0.10026 0.21578 0.01059 0.12879 0.12038 0.08685 0.02817]
 [0.18938 0.00952 0.06538 0.04877 0.10008 0.21716 0.01091 0.12490 0.12029 0.08550 0.02812]
 [0.18772 0.00914 0.06234 0.05088 0.09816 0.21867 0.01075 0.12498 0.12030 0.08956 0.02750]
 [0.19370 0.00929 0.06394 0.04817 0.09925 0.21553 0.01091 0.12343 0.12321 0.08497 0.02760]
 [0.18832 0.00914 0.06271 0.05072 0.09936 0.21617 0.01052 0.12407 0.12129 0.09021 0.02748]
 [0.18758 0.00960 0.06583 0.04972 0.10150 0.21636 0.01058 0.12314 0.11926 0.08811 0.02831]
 [0.18833 0.00918 0.06284 0.04999 0.09764 0.21915 0.01104 0.12664 0.12057 0.08708 0.02754]
 [0.18783 0.00939 0.06386 0.04981 0.09796 0.22086 0.01114 0.12606 0.11886 0.08632 0.02790]
 [0.18845 0.00917 0.06275 0.04991 0.09769 0.21899 0.01089 0.12652 0.12079 0.08720 0.02764]
 [0.19083 0.00930 0.06384 0.04899 0.09892 0.21705 0.01093 0.12479 0.12167 0.08598 0.02769]
 [0.18656 0.00940 0.06527 0.04879 0.09995 0.21

It is obvious that all entries of $p^{10}$ are positive. So, the chain is regular.

## 2.  Calculate the  steady state vector  $\alpha$ 

Calculate (approximately) the steady state vector $\alpha$ of the chain by calculation of $P^k$ for enough large $t$.

In [4]:
# Calculate the t-th power of the P matrix and analyze its results.
t = 40
P_50 = matrix_power(P, t)
print(f'P_50 Matrix = \n{P_50}')

P_50 Matrix = 
[[0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0

Define some methods to check $\alpha$.

In [5]:
# Detect whether the probability vector distribution of each row of alpha is consistent.
def check_each_row_same_probability(alpha: np.ndarray):
    epsilon = 1e-3
    return (np.sum(alpha, 1) - 1.0 < epsilon).all()

assert check_each_row_same_probability(P_50)

# Check alpha are positive
print((P_50 >= 0).all())
assert (P_50 >= 0).all()
print("alpha is positive")

True
alpha is positive


Check if alpha contains a stable vector.

In [6]:
def check_significance_digits_mae(matrix):
    # Initialize an empty array to store the MAE of each row compared with other rows
    row_maes = np.zeros((len(matrix), len(matrix)))

    # Calculate MAE for each row compared with every other row
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if i != j:
                row_maes[i, j] = np.mean(np.abs(matrix[i] - matrix[j]))

    # Calculate the average MAE, ignoring the diagonal (comparison of the row with itself)
    np.fill_diagonal(row_maes, np.nan)
    average_mae = np.nanmean(row_maes)

    # Determine if the average MAE is within the desired precision
    accuracy_3_digits = average_mae < 0.001
    accuracy_4_digits = average_mae < 0.0001

    return accuracy_3_digits and accuracy_4_digits

assert check_significance_digits_mae(P_50)
print(f"Rows of Pt for t={t} are equal to an accuracy of 3-4 significance digits")

Rows of Pt for t=40 are equal to an accuracy of 3-4 significance digits


## 2.  Calculate the mean first passage matrix  $𝐸$

We calculate the mean first passage matrix $𝐸$ in several steps.

In [7]:
# w can be taken as approximation of the limiting vector alpha
w = P_50[0]
print(f'w = {w}')

w = [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]


In [8]:
# Check w = w * P
epsilon = 1e-4
assert (np.dot(w, P) - w < epsilon).all()

So, vector $w$ can be taken as an approximation of the limiting vector $\alpha$.The mean first passage matrix is calculated using the following formula.

In [9]:
# Identity matrix I
I = np.eye(w.shape[0])
print(f"Identity matrix I = \n{I}")

Identity matrix I = 
[[1.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 1.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 1.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 1.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 1.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 1.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 1.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 1.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 1.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 1.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.0

In [10]:
# W matrix
W = np.tile(w, (w.shape[0], 1))
print(f"W = \n{W}")

W = 
[[0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.02792]
 [0.18793 0.00935 0.06424 0.04970 0.09950 0.21732 0.01075 0.12555 0.12035 0.08739 0.0

In [11]:
# Diagonal matrix D
D = np.diag(1 / w)
print(f"Diagonal matrix D = \n{D}")

Diagonal matrix D = 
[[5.32100 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 106.91190 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 15.56705 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 20.12221 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 10.05008 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 4.60159 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 92.99140 0.00000 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 7.96487 0.00000 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 8.30939 0.00000 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 11.44273 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00

In [12]:
# Fundamental matrix
Z = np.linalg.inv(I - (P - W))
print(f"Fundamental matrix Z = \n{Z}")

Fundamental matrix Z = 
[[0.78786 0.00634 0.06166 0.11870 0.02389 -0.04108 -0.00815 -0.14929 0.02007 0.17324 0.00675]
 [-0.06473 1.28406 0.43689 -0.07346 -0.13310 -0.21784 -0.02153 -0.25140 0.14572 -0.07664 -0.02797]
 [0.18647 -0.01700 0.91224 -0.00366 -0.14056 0.19045 -0.00356 -0.01552 -0.08273 -0.04480 0.01867]
 [-0.06980 -0.02819 0.31210 0.91497 0.23769 0.11288 -0.03270 -0.06034 -0.18021 -0.14942 -0.05698]
 [0.05176 -0.02063 -0.14424 -0.06611 0.80128 0.46594 -0.03981 0.14364 -0.03765 -0.07877 -0.07542]
 [-0.00628 -0.01919 -0.14357 -0.07704 -0.15446 1.00829 -0.03843 0.45697 0.11079 -0.06525 -0.07185]
 [-0.34188 -0.04089 -0.06092 0.09446 0.37441 -0.08223 1.21919 -0.17306 -0.31804 -0.26800 0.59694]
 [0.27781 -0.00432 -0.04303 -0.00117 0.00852 -0.29201 -0.02139 0.70575 0.32381 0.07364 -0.02761]
 [0.17216 0.00384 -0.01566 -0.01545 0.18470 -0.10532 -0.01290 -0.18640 0.83068 0.14990 -0.00556]
 [-0.17100 0.07443 0.28176 -0.01691 0.15932 -0.02927 0.06244 -0.14246 -0.21778 0.80946 0.19001]
 [

In [13]:
# J_dg matrix
J = np.ones_like(Z)
JZ_dg = np.copy(J)
np.fill_diagonal(JZ_dg, np.diag(Z))
print(f"J_dg = \n{JZ_dg}")

J_dg = 
[[0.78786 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.28406 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.00000 0.91224 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.00000 1.00000 0.91497 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.00000 1.00000 1.00000 0.80128 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.00000 1.00000 1.00000 1.00000 1.00829 1.00000 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.21919 1.00000 1.00000 1.00000 1.00000]
 [1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 0.70575 1.00000 1.00000 1.00000]
 [1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 0.83068 1.00000 1.00000]
 [1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 0.80946 1.00000]
 [1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 1.00000 

In [15]:
# Mean first passage matrix Z
E = (I - Z + JZ_dg) @ D
print(f"Mean first passage matrix Z = \n{E}")

Mean first passage matrix Z = 
[[5.32100 106.23397 14.60717 17.73362 9.81000 4.79064 93.74960 9.15392 8.14258 9.46034 35.57853]
 [5.66540 106.91190 8.76592 21.60038 11.38779 5.60400 94.99338 9.96727 7.09855 12.31972 36.82231]
 [4.32882 108.72898 15.56705 20.19582 11.46271 3.72522 93.32263 8.08849 8.99684 11.95535 35.15156]
 [5.69239 109.92618 10.70853 20.12221 7.66130 4.08217 96.03228 8.44545 9.80683 13.15255 37.86121]
 [5.04557 109.11774 17.81244 21.45239 10.05008 2.45751 96.69307 6.82079 8.62224 12.34411 38.52199]
 [5.35439 108.96303 17.80200 21.67237 11.60239 4.60159 96.56515 4.32513 7.38876 12.18940 38.39408]
 [7.14013 111.28302 16.51535 18.22155 6.28723 4.97996 92.99140 9.34324 10.95212 14.50938 14.43756]
 [3.84275 107.37374 16.23687 20.14584 9.96449 5.94528 94.98034 7.96487 5.61875 10.60011 36.80927]
 [4.40493 106.50113 15.81082 20.43303 8.19384 5.08623 94.19066 9.44951 8.30939 9.72750 36.01958]
 [6.23090 98.95394 11.18088 20.46248 8.44887 4.73628 87.18517 9.09956 10.11903 11.442